### PR TITLE
Add comparison and plot functions for droplet diagnostic

### PR DESCRIPTION
**Pull request by sjsprecious**
This PR updates the verification framework to post-process the droplet diagnostic output.
- For the 0th-order droplet diagnostic, we focus on the four variables with largest relative errors (it could be fewer than four if two simulations agree very well with each other).
- For the 1st-order droplet diagnostic, we focus on the four variables with largest relative errors (it could be different variables at different levels for each pair of comparison).
- For both 0th-order and 1st-order droplet diagnostic, the selected variables could be different between different configurations. Thus we will calculate the statistics and make plots individually for each pair of comparison.
- Some minor fixes to the `runit.py` script.

An example of plot for the 0th-order droplet diagnostic between a CPU run (intel) and MPI+OpenACC run looks like:
image

An example of plot for the 1st-order droplet diagnostic between a CPU run (intel) and MPI+OpenACC run looks like:
image

### CODE REVIEW

**Review by sherimickelson — APPROVED** [review]
Thanks @sjsprecious .  I don't have any droplet output to fully test this, but my test without that data runs okay.  It should be okay to merge.

**Review by johnmauff — COMMENTED** [review]
@sjsprecious, would it be possible to attach a sample diagnostic plot that is generated by this PR?

**Comment by sjsprecious** [comment]
@sherimickelson @johnmauff Thanks for your quick reply and comments. I have updated two example diagnostic plots generated by this PR.

**Review by johnmauff — APPROVED** [review]
@sjsprecious thanks for adding the plot.  This PR now looks great.

**Pull request merged**
