### PR TITLE
Further clean up of runit script

### PR DESCRIPTION
**Pull request by sjsprecious**
A few minor updates based on the PR https://github.com/sherimickelson/CM1_benchmarkingWF/pull/10:

- clean up some namelist options
- remove unused arguments
- remove unused python modules
- Update `FC` to `nvfortran` for GPU run by default
- rename `runit` to `runit.py`
- add compiler, machine and hardware information to `log_fn` instead so that the control and experiment tests are still in the same pair in the json file

### CODE REVIEW

**Review by sherimickelson — APPROVED** [review]
Thanks, @sjsprecious  for cleaning the scripts up!  For some reason I needed to add the module script from the systems group in order for the module load operation to work.  I'm guessing because I'm running tcsh and the python script uses sh.  But other than that, everything else looks good and you can go ahead and merge these changes in along with the one addition I made.

**Comment by sjsprecious** [comment]
Thanks @sherimickelson for your update. Do you mean that `os.system` will use `bash` be default?

**Comment by sherimickelson** [comment]
@sjsprecious , I believe so.  I saw this error without my addition
```
$DEBUG_L is []
$USE_MPI_L is []
$FC is [ifort]
$OPTS is [ -g -O3 -xHost -ip -assume byterecl -fp-model precise -ftz -init=snan,arrays -traceback]
$CPP is [ cpp -C -P -traditional -Wno-invalid-pp-token -ffreestanding]
$OMP is []
$DM is []
rm -f *.f90 *.o *.a *.mod
sh: module: command not found
sh: module: command not found
```

**Comment by sjsprecious** [comment]
Thanks @sherimickelson . It is good to know that and thank you for fixing it.

**Pull request merged**
